# Generated by Django 6.0.1 on 2026-02-03 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="opencourtapplication",
            index=models.Index(fields=["police_station"], name="idx_police_station"),
        ),
        migrations.AddIndex(
            model_name="opencourtapplication",
            index=models.Index(fields=["division"], name="idx_division"),
        ),
        migrations.AddIndex(
            model_name="opencourtapplication",
            index=models.Index(fields=["category"], name="idx_category"),
        ),
        migrations.AddIndex(
            model_name="opencourtapplication",
            index=models.Index(fields=["status"], name="idx_status"),
        ),
        migrations.AddIndex(
            model_name="opencourtapplication",
            index=models.Index(fields=["feedback"], name="idx_feedback"),
        ),
        migrations.AddIndex(
            model_name="opencourtapplication",
            index=models.Index(fields=["date"], name="idx_date"),
        ),
        migrations.AddIndex(
            model_name="opencourtapplication",
            index=models.Index(fields=["created_at"], name="idx_created_at"),
        ),
        migrations.AddIndex(
            model_name="opencourtapplication",
            index=models.Index(fields=["sr_no"], name="idx_sr_no"),
        ),
        migrations.AddIndex(
            model_name="opencourtapplication",
            index=models.Index(fields=["dairy_no"], name="idx_dairy_no"),
        ),
        migrations.AddIndex(
            model_name="opencourtapplication",
            index=models.Index(fields=["name"], name="idx_name"),
        ),
        migrations.AddIndex(
            model_name="opencourtapplication",
            index=models.Index(
                fields=["police_station", "status"], name="idx_ps_status"
            ),
        ),
        migrations.AddIndex(
            model_name="opencourtapplication",
            index=models.Index(
                fields=["status", "feedback"], name="idx_status_feedback"
            ),
        ),
    ]
